/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Book;
import controller.BookController;
import model.session;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.util.List;
import controller.UserBookController;

/**
 *
 * @author USER
 */
public class bookhome extends javax.swing.JFrame {


    private BookController bookController;
    /**
     * Creates new form bookhome
     */
    public bookhome() {
        initComponents();
        bookController = new BookController();
        loadBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadBooks() {
        try {
            List<Book> books = bookController.getAllBooks();

            jPanel1.removeAll();

            // Set GridLayout with 3 columns and rows auto (0)
         jPanel1.setLayout(new FlowLayout(FlowLayout.LEFT, 30, 15));


            for (Book book : books) {
                jPanel1.add(createBookPanel(book));
            }

            jPanel1.revalidate();
            jPanel1.repaint();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading books: " + e.getMessage());
        }
    }

    private JPanel createBookPanel(Book book) {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBorder(BorderFactory.createLineBorder(Color.GRAY));

        // Book Image
        JLabel imageLabel = new JLabel();
        ImageIcon icon = loadImageIcon(book.getImagePath(), 120, 160);
        if (icon != null) {
            imageLabel.setIcon(icon);
            imageLabel.setHorizontalAlignment(JLabel.CENTER);
        } else {
            imageLabel.setText("No Image");
            imageLabel.setHorizontalAlignment(JLabel.CENTER);
        }
        panel.add(imageLabel, BorderLayout.NORTH);

        // Title and description in JTextArea (wrap text)
        JTextArea infoArea = new JTextArea(book.getTitle() + "\n\n" + book.getDescription() + "\n\n" + book.getpric()+" LKR");
        infoArea.setLineWrap(true);
        infoArea.setWrapStyleWord(true);
        infoArea.setEditable(false);
        infoArea.setBackground(panel.getBackground());
        infoArea.setMargin(new Insets(5,5,5,5));
        panel.add(infoArea, BorderLayout.CENTER);

        // Stock status button
        JButton stockBtn = new JButton(book.getQuantity() > 0 ? "In Stock" : "Out of Stock");
        stockBtn.setBackground(book.getQuantity() > 0 ? Color.GREEN : Color.RED);
        stockBtn.setForeground(Color.WHITE);
        stockBtn.addActionListener(evt -> {
   if (session.isLoggedIn()) {
       String id;
     // int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to proceed?", "Confirm", JOptionPane.YES_NO_OPTION);
      int bookid = book.getId();
     int result= JOptionPane.showConfirmDialog(null, "please conform payment" +bookid, "confirm" ,JOptionPane.YES_NO_OPTION);
if (result == JOptionPane.YES_OPTION) {
    

            UserBookController bookUserController = new UserBookController();
          String userEmail = session.getCurrentEmail();  // assign the logged-in user's email
bookUserController.borrowBook(book, userEmail);

        loadBooks();
        
            JOptionPane.showMessageDialog(this, "Borrowed successfully!");
            loadBooks(); // refresh UI
    // proceed with action
} else {
    // User clicked NO or closed the dialog
    System.out.println("User cancelled.");
    // cancel the action
}

    } else {
        JOptionPane.showMessageDialog(null, "Please log in first!");
       Login f1 = new Login();
        f1.setVisible(true);
        this.setVisible(false);
    }

});
        panel.add(stockBtn, BorderLayout.SOUTH);

        return panel;
    }

    private ImageIcon loadImageIcon(String path, int width, int height) {
        if (path == null || path.trim().isEmpty()) return null;

        File imgFile = new File(path);
        if (!imgFile.exists()) return null;

        ImageIcon icon = new ImageIcon(path);
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

   

        // TODO add your handling code here:
                                    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setText("welcome to library . feel free to borrow any of our books!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(345, 345, 345))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookhome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            // Ignore and use default
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookhome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
